@Library('sharedlibraries')_
pipeline
{
    agent any
    stages
    {
        stage('ContinuousDownload')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/Gopi806/maven.git")
                }
            }
        }
        stage('ContinuousBuild')
        {
            steps
            {
                script
                {
                    cicd.newMaven()
                }
            }
        }
        stage('ContinuousDeployment')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("172.31.3.201","testapp")
                }
            }
        }
        stage('ContinuousTesting')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/intelliqittrainings/FunctionalTesting.git")
                    cicd.runSelenium("/home/ubuntu/.jenkins/workspace/Pipelinewithlibraries")
                }
            }
        }
        stage('ContinuousDelivery')
        {
            steps
            {
                script
                {
                    cicd.newApprovals("anitha")
                    cicd.newDeploy("172.31.2.229","prodapp")
                }
            }
        }
    }
    }
